version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    env_file:
      - .development.env
    ports:
      - "3030:3030"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: my_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
